/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zumans1;
    
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.application.Platform.exit;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
 
/**
 *
 * @author agila
 */
public class ZUMANS_MENU_PAGE extends javax.swing.JFrame {
int  volumem=1;
    int level=3;
   

    /**
     * Creates new form ZUMANS_MENU_PAGE
     */
    public ZUMANS_MENU_PAGE() {
        try {
            
            this.setIconImage(ImageIO.read(new File("C:\\ZUMANS\\images_zumans\\screenshot_2021-04-06-13-09-58.png")));
            initComponents();
            custom_cursor();
            Pstory.setVisible(false);
            jScrollPane2.setVisible(false);
            this.setExtendedState(this.MAXIMIZED_BOTH);
           
        } catch (IOException ex) {
            Logger.getLogger(ZUMANS_MENU_PAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void custom_cursor(){
       Toolkit tk=Toolkit.getDefaultToolkit();
       Image Icur=tk.getImage("C:\\ZUMANS\\images_zumans\\cursor.png");
       Point point=new Point(0,0);
       Cursor Ccur=tk.createCustomCursor(Icur, point, "CURSOR");
       setCursor(Ccur);
   }
    AudioInputStream audio=null;
    Clip clip=null;
    public void playsound(String url){
        if(volumem==1){
            File audioFile = new File(url);
 
        try {
             audio = AudioSystem.getAudioInputStream(audioFile);
            clip=AudioSystem.getClip();
            clip.open(audio);
            clip.loop(Clip.LOOP_CONTINUOUSLY);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(ZUMANS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ZUMANS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(ZUMANS.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Pstory = new javax.swing.JPanel();
        Bback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Bstart = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Psettings = new javax.swing.JPanel();
        Bback1 = new javax.swing.JButton();
        TBvolumeswitch = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Slevel = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".ZUMANS.");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1948, 1006));
        setSize((int)(Toolkit.getDefaultToolkit().getScreenSize().getWidth()-50),(int)(Toolkit.getDefaultToolkit().getScreenSize().getHeight()-150));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Adobe Devanagari", 3, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ZUMANS\\images_zumans\\new.jpg")); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 4, true));
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 1190, 710));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("$.STORY.$");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 4, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 820, 260, 50));

        Pstory.setBackground(new java.awt.Color(0, 0, 0));
        Pstory.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 16)); // NOI18N

        Bback.setBackground(new java.awt.Color(0, 0, 0));
        Bback.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        Bback.setForeground(new java.awt.Color(255, 0, 51));
        Bback.setText("$.HIDE.$");
        Bback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 4, true));
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 21)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("INTRODUCTION:\n\n...->WITH SOME UNKNOWN REASON,THE\nZOMBIE APPOCALYPSE HAS STARTED..,\n& AS A POLICE OFFICER IT IS \nUR RESPONSIBILITY TO GUIDE & \nSAVE THE PEOPLE..................\n...->FOR THAT TAKE THEM TO THEM\nTO THE BUIDING NEAR THAT ENOUGH..\n...->REMEMBER THE ZOMBIE EFFECT \nIS CONTAGIOUS..THAT IS IF ANY \nZOMBIE BITS ANY HUMAN THEN HE/SHE\nWILL ALSO BECOME A ZOMBIE.SO ACT\nSOON.............................\n.................................\nPROCESS:\n\n.->THE MORE YOU SAVE THE PEOPLE \n& KILL THE ZOMBIES,UR POINTS \n& SO UR LEVEL GET INCREASES..\n.->THE ZOMBIES WILL FIND HUMANS\nWITHIN A SPECIFIC RANGE & GOES\nTOWARDS THEM...................\n.->TO GUIDE A HUMAN TO ANYWHERE\nJUST GO NEAR THAT ONE AND HE/SHE\nWILL START TO CONTINUE U.......\n................................\nATTACK:\n\n  COMBAT:\n.->U CAN DIRECTLY COMBAT WITH THE\nZOMBIES,BUT DON'T FORGET,IN THIS \nPROCCESS UR HEALTH WILL ALSO GETS\nREDUCED...FOR THIS JUST GO NEAR TO\nA ZOMBIE..........................\n  WEPOEN:\n.->WITH A GUN U CAN SHOOT ZOMBIES\nFROM A DISTANCE,TAKE CARE TO CHECK\nTHE BUULETS AND RANGE OF THE GUN..\n..................................\nHEALTH_RECHARGE:\n\n.->U CAN INCREASE UR HEALTH BY \nHAVING THE FOODS AND MEDICNE OFTEN\n...............................\nCONCLUSION:\n\n.->THIS ALL GETS OVER ONCE U GOT\nTHE VACCINE(ALL ZOMBIES CAN BE\nCURED AND THIS GAME WILL BE OVER)\nIN THE BIO-TECHNOLLGYLAB,FOR THIS \nU HAVE TO INCREASE UR LEVEL.....\n\n...............................");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        jTextArea1.setCaretPosition(0);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout PstoryLayout = new javax.swing.GroupLayout(Pstory);
        Pstory.setLayout(PstoryLayout);
        PstoryLayout.setHorizontalGroup(
            PstoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PstoryLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Bback, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        PstoryLayout.setVerticalGroup(
            PstoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PstoryLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel1.add(Pstory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 80, 450, 960));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\ZUMANS\\images_zumans\\screenshot_2021-04-06-13-09-58.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 0, 70, 80));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\ZUMANS\\images_zumans\\zombie_70px.png")); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 770, 62, 63));

        jLabel4.setBackground(new java.awt.Color(255, 0, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\ZUMANS\\images_zumans\\second.gif")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 780, 320, 180));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setText("$.QUIT.$");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 4, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 900, 260, 50));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 51));
        jButton5.setText("$.SETTINGS.$");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 4, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 900, 260, 50));

        Bstart.setBackground(new java.awt.Color(0, 0, 0));
        Bstart.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        Bstart.setForeground(new java.awt.Color(255, 0, 51));
        Bstart.setText("$.START.$");
        Bstart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 4, true));
        Bstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BstartActionPerformed(evt);
            }
        });
        jPanel1.add(Bstart, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 820, 260, 50));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        Psettings.setBackground(new java.awt.Color(0, 0, 0));
        Psettings.setForeground(new java.awt.Color(255, 0, 0));
        Psettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bback1.setBackground(new java.awt.Color(0, 0, 0));
        Bback1.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        Bback1.setForeground(new java.awt.Color(255, 0, 51));
        Bback1.setText("$.HIDE.$");
        Bback1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 4, true));
        Bback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bback1ActionPerformed(evt);
            }
        });
        Psettings.add(Bback1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 144, 43));

        TBvolumeswitch.setBackground(new java.awt.Color(0, 0, 0));
        TBvolumeswitch.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 20)); // NOI18N
        TBvolumeswitch.setForeground(new java.awt.Color(255, 0, 0));
        TBvolumeswitch.setSelected(true);
        TBvolumeswitch.setText("ON");
        TBvolumeswitch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        TBvolumeswitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBvolumeswitchActionPerformed(evt);
            }
        });
        Psettings.add(TBvolumeswitch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 62, 73, 60));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("LEVEL.........->");
        Psettings.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 159, 136, 62));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("VOLUME.....->");
        Psettings.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 62, -1, 62));

        Slevel.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 20)); // NOI18N
        Slevel.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        Slevel.setAutoscrolls(true);
        Slevel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        Slevel.setValue(3);
        Psettings.add(Slevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 70, 50));

        jScrollPane2.setViewportView(Psettings);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 290, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Pstory.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        Pstory.setVisible(false);
    }//GEN-LAST:event_BbackActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clip.stop();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jScrollPane2.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BstartActionPerformed
        clip.stop();
        try {
            Slevel.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(ZUMANS_MENU_PAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
        level = (Integer)Slevel.getValue();
                System.out.println(level);
                this.dispose();
        new ZUMANS().setVisible(true);
    }//GEN-LAST:event_BstartActionPerformed

    private void Bback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bback1ActionPerformed
       jScrollPane2.setVisible(false);
    }//GEN-LAST:event_Bback1ActionPerformed

    private void TBvolumeswitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBvolumeswitchActionPerformed
        if(volumem==1){
            clip.stop();
            TBvolumeswitch.setText("OFF");
            volumem=0;
        }
        else{
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            TBvolumeswitch.setText("ON");
            volumem=1;
        }
        
    }//GEN-LAST:event_TBvolumeswitchActionPerformed

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        playsound("C:\\ZUMANS\\audios_zumans\\Intro00.wav");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       clip.stop();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ZUMANS_MENU_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ZUMANS_MENU_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ZUMANS_MENU_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ZUMANS_MENU_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ZUMANS_MENU_PAGE().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JButton Bback1;
    private javax.swing.JButton Bstart;
    private javax.swing.JPanel Psettings;
    private javax.swing.JPanel Pstory;
    private javax.swing.JSpinner Slevel;
    private javax.swing.JToggleButton TBvolumeswitch;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
