/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zumans1;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;

/**
 *
 * @author agila
 */
public class ZUMANS_CHARACTER_PAGE extends javax.swing.JFrame {

    /**
     * Creates new form ZUMANS_CHARACTER_PAGE
     */
    public ZUMANS_CHARACTER_PAGE() {
        try {
            this.setIconImage(ImageIO.read(new File("C:\\ZUMANS\\images_zumans\\screenshot_2021-04-06-13-09-58.png")));
            initComponents();
            custom_cursor();
        } catch (IOException ex) {
            Logger.getLogger(ZUMANS_CHARACTER_PAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    public void setPage(int ldistance,boolean ldistanceT,int lhealthT,int lhealth,int lpointsT,int lpoints,boolean lwhoT,String lwho,Icon limage){
        Ldistance.setText(String.valueOf(ldistance));
        Ldistance.setVisible(ldistanceT);
        LdistanceT.setVisible(ldistanceT);
        if(lhealthT==0) LhealthT.setText("   RANGE                         ->");
        Lhealth.setText(String.valueOf(lhealth));
        Bimage.setIcon(limage);
        if(lwhoT==false) LwhoT.setText("   WHAT                         ->");
        Lpoints.setText(String.valueOf(lpoints));
        if(lpointsT==0) LpointsT.setText("   BULLETS                         ->");
        if(lpointsT<0) {
            LpointsT.setVisible(false);
            Lpoints.setVisible(false);
        }
        Lwho.setText(String.valueOf(lwho));
    }
    public void custom_cursor(){
       Toolkit tk=Toolkit.getDefaultToolkit();
       Image Icur=tk.getImage("C:\\ZUMANS\\images_zumans\\cursor.png");
       Point point=new Point(0,0);
       Cursor Ccur=tk.createCustomCursor(Icur, point, "CURSOR");
       setCursor(Ccur);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LwhoT = new javax.swing.JLabel();
        Lwho = new javax.swing.JLabel();
        LhealthT = new javax.swing.JLabel();
        Lhealth = new javax.swing.JLabel();
        LpointsT = new javax.swing.JLabel();
        Lpoints = new javax.swing.JLabel();
        LdistanceT = new javax.swing.JLabel();
        Ldistance = new javax.swing.JLabel();
        Bimage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".ZUMANS.");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LwhoT.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        LwhoT.setForeground(new java.awt.Color(255, 0, 51));
        LwhoT.setText("    WHO                         ->");
        LwhoT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel1.add(LwhoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 276, 354, 49));

        Lwho.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        Lwho.setForeground(new java.awt.Color(255, 0, 51));
        Lwho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel1.add(Lwho, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 276, 189, 49));

        LhealthT.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        LhealthT.setForeground(new java.awt.Color(255, 0, 51));
        LhealthT.setText("    HEALTH                 ->");
        LhealthT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel1.add(LhealthT, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 334, 354, 49));

        Lhealth.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        Lhealth.setForeground(new java.awt.Color(255, 0, 51));
        Lhealth.setText("    ");
        Lhealth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel1.add(Lhealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 334, 189, 49));

        LpointsT.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        LpointsT.setForeground(new java.awt.Color(255, 0, 51));
        LpointsT.setText("    POINTS                    ->");
        LpointsT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel1.add(LpointsT, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 392, 354, 49));

        Lpoints.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        Lpoints.setForeground(new java.awt.Color(255, 0, 51));
        Lpoints.setText("                             ");
        Lpoints.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel1.add(Lpoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 392, 189, 49));

        LdistanceT.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        LdistanceT.setForeground(new java.awt.Color(255, 0, 51));
        LdistanceT.setText("    DISTANCE AWAY FROM PLAYER    ->");
        LdistanceT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        jPanel1.add(LdistanceT, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 450, 354, 51));

        Ldistance.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        Ldistance.setForeground(new java.awt.Color(255, 0, 51));
        Ldistance.setText("                              ");
        Ldistance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        jPanel1.add(Ldistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 451, 189, 49));

        Bimage.setBackground(new java.awt.Color(0, 0, 0));
        Bimage.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24)); // NOI18N
        Bimage.setForeground(new java.awt.Color(255, 0, 51));
        Bimage.setText(" ");
        Bimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 4, true));
        Bimage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BimageActionPerformed(evt);
            }
        });
        jPanel1.add(Bimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 104, 84, 98));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BimageActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BimageActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ZUMANS_CHARACTER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ZUMANS_CHARACTER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ZUMANS_CHARACTER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ZUMANS_CHARACTER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ZUMANS_CHARACTER_PAGE().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bimage;
    private javax.swing.JLabel Ldistance;
    private javax.swing.JLabel LdistanceT;
    private javax.swing.JLabel Lhealth;
    private javax.swing.JLabel LhealthT;
    private javax.swing.JLabel Lpoints;
    private javax.swing.JLabel LpointsT;
    private javax.swing.JLabel Lwho;
    private javax.swing.JLabel LwhoT;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
